# Generated by Django 2.2.2 on 2019-09-29 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='calendarOwnerTID',
            field=models.IntegerField(default=318093217, editable=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='calendarUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
