# Generated by Django 2.2.6 on 2019-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190930_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='calendarOwnerTID',
            field=models.IntegerField(default=990292248, editable=False),
        ),
    ]
