# Generated by Django 2.2.2 on 2019-12-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191202_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'room images'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='room',
            name='videoConferecingOption',
            field=models.BooleanField(default=False, help_text='if this option is checked Time limit for schedules of up to 4 hours per period (morning and afternoon)', verbose_name='video conferecing option'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='calendarOwnerTID',
            field=models.IntegerField(default=1026365590, editable=False),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='core.Room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='roomproperty',
            name='value',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Name'),
        ),
    ]
