# Generated by Django 2.2.2 on 2019-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191203_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='calendarOwnerTID',
            field=models.IntegerField(default=1658648889, editable=False),
        ),
    ]
